# Generated by Django 2.0.6 on 2018-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_auto_20181016_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel2',
            name='establishedDate',
            field=models.DateField(),
        ),
    ]
