# Generated by Django 2.0.6 on 2018-10-16 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_auto_20181016_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel2',
            name='establishedDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
